// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: backend.api.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------
type WebProtocol int32

const (
	WebProtocol_HTTP  WebProtocol = 0
	WebProtocol_HTTPS WebProtocol = 1
)

// Enum value maps for WebProtocol.
var (
	WebProtocol_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
	}
	WebProtocol_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
	}
)

func (x WebProtocol) Enum() *WebProtocol {
	p := new(WebProtocol)
	*p = x
	return p
}

func (x WebProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_proto_enumTypes[0].Descriptor()
}

func (WebProtocol) Type() protoreflect.EnumType {
	return &file_backend_api_proto_enumTypes[0]
}

func (x WebProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebProtocol.Descriptor instead.
func (WebProtocol) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HideId        string                 `protobuf:"bytes,1,opt,name=hideId,proto3" json:"hideId,omitempty"`
	BeeId         string                 `protobuf:"bytes,2,opt,name=beeId,proto3" json:"beeId,omitempty"`
	WebPort       int32                  `protobuf:"varint,3,opt,name=webPort,proto3" json:"webPort,omitempty"`
	WebProtocol   WebProtocol            `protobuf:"varint,4,opt,name=webProtocol,proto3,enum=backend.WebProtocol" json:"webProtocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_backend_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHideId() string {
	if x != nil {
		return x.HideId
	}
	return ""
}

func (x *RegisterRequest) GetBeeId() string {
	if x != nil {
		return x.BeeId
	}
	return ""
}

func (x *RegisterRequest) GetWebPort() int32 {
	if x != nil {
		return x.WebPort
	}
	return 0
}

func (x *RegisterRequest) GetWebProtocol() WebProtocol {
	if x != nil {
		return x.WebProtocol
	}
	return WebProtocol_HTTP
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_backend_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ------
type CallbackPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HideId        string                 `protobuf:"bytes,1,opt,name=hideId,proto3" json:"hideId,omitempty"`
	BeeId         string                 `protobuf:"bytes,2,opt,name=beeId,proto3" json:"beeId,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackPushRequest) Reset() {
	*x = CallbackPushRequest{}
	mi := &file_backend_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackPushRequest) ProtoMessage() {}

func (x *CallbackPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackPushRequest.ProtoReflect.Descriptor instead.
func (*CallbackPushRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackPushRequest) GetHideId() string {
	if x != nil {
		return x.HideId
	}
	return ""
}

func (x *CallbackPushRequest) GetBeeId() string {
	if x != nil {
		return x.BeeId
	}
	return ""
}

func (x *CallbackPushRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CallbackPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackPushResponse) Reset() {
	*x = CallbackPushResponse{}
	mi := &file_backend_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackPushResponse) ProtoMessage() {}

func (x *CallbackPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackPushResponse.ProtoReflect.Descriptor instead.
func (*CallbackPushResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_rawDescGZIP(), []int{3}
}

func (x *CallbackPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallbackPushResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_backend_api_proto protoreflect.FileDescriptor

const file_backend_api_proto_rawDesc = "" +
	"\n" +
	"\x11backend.api.proto\x12\abackend\"\x91\x01\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06hideId\x18\x01 \x01(\tR\x06hideId\x12\x14\n" +
	"\x05beeId\x18\x02 \x01(\tR\x05beeId\x12\x18\n" +
	"\awebPort\x18\x03 \x01(\x05R\awebPort\x126\n" +
	"\vwebProtocol\x18\x04 \x01(\x0e2\x14.backend.WebProtocolR\vwebProtocol\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x13CallbackPushRequest\x12\x16\n" +
	"\x06hideId\x18\x01 \x01(\tR\x06hideId\x12\x14\n" +
	"\x05beeId\x18\x02 \x01(\tR\x05beeId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"H\n" +
	"\x14CallbackPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors*\"\n" +
	"\vWebProtocol\x12\b\n" +
	"\x04HTTP\x10\x00\x12\t\n" +
	"\x05HTTPS\x10\x012\xf7\x01\n" +
	"\n" +
	"BackendApi\x12?\n" +
	"\bRegister\x12\x18.backend.RegisterRequest\x1a\x19.backend.RegisterResponse\x12N\n" +
	"\x0fPushUrlCallback\x12\x1c.backend.CallbackPushRequest\x1a\x1d.backend.CallbackPushResponse\x12X\n" +
	"\x19PushWaitingScreenCallback\x12\x1c.backend.CallbackPushRequest\x1a\x1d.backend.CallbackPushResponseB\x13Z\x11./backend;backendb\x06proto3"

var (
	file_backend_api_proto_rawDescOnce sync.Once
	file_backend_api_proto_rawDescData []byte
)

func file_backend_api_proto_rawDescGZIP() []byte {
	file_backend_api_proto_rawDescOnce.Do(func() {
		file_backend_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_api_proto_rawDesc), len(file_backend_api_proto_rawDesc)))
	})
	return file_backend_api_proto_rawDescData
}

var file_backend_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backend_api_proto_goTypes = []any{
	(WebProtocol)(0),             // 0: backend.WebProtocol
	(*RegisterRequest)(nil),      // 1: backend.RegisterRequest
	(*RegisterResponse)(nil),     // 2: backend.RegisterResponse
	(*CallbackPushRequest)(nil),  // 3: backend.CallbackPushRequest
	(*CallbackPushResponse)(nil), // 4: backend.CallbackPushResponse
}
var file_backend_api_proto_depIdxs = []int32{
	0, // 0: backend.RegisterRequest.webProtocol:type_name -> backend.WebProtocol
	1, // 1: backend.BackendApi.Register:input_type -> backend.RegisterRequest
	3, // 2: backend.BackendApi.PushUrlCallback:input_type -> backend.CallbackPushRequest
	3, // 3: backend.BackendApi.PushWaitingScreenCallback:input_type -> backend.CallbackPushRequest
	2, // 4: backend.BackendApi.Register:output_type -> backend.RegisterResponse
	4, // 5: backend.BackendApi.PushUrlCallback:output_type -> backend.CallbackPushResponse
	4, // 6: backend.BackendApi.PushWaitingScreenCallback:output_type -> backend.CallbackPushResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_api_proto_init() }
func file_backend_api_proto_init() {
	if File_backend_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_api_proto_rawDesc), len(file_backend_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_api_proto_goTypes,
		DependencyIndexes: file_backend_api_proto_depIdxs,
		EnumInfos:         file_backend_api_proto_enumTypes,
		MessageInfos:      file_backend_api_proto_msgTypes,
	}.Build()
	File_backend_api_proto = out.File
	file_backend_api_proto_goTypes = nil
	file_backend_api_proto_depIdxs = nil
}
