// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: bee.api.proto

package bee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------
type PushUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushUrlRequest) Reset() {
	*x = PushUrlRequest{}
	mi := &file_bee_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUrlRequest) ProtoMessage() {}

func (x *PushUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUrlRequest.ProtoReflect.Descriptor instead.
func (*PushUrlRequest) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{0}
}

func (x *PushUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PushUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushUrlResponse) Reset() {
	*x = PushUrlResponse{}
	mi := &file_bee_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUrlResponse) ProtoMessage() {}

func (x *PushUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUrlResponse.ProtoReflect.Descriptor instead.
func (*PushUrlResponse) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{1}
}

// ------
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_bee_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            bool                   `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_bee_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

// ------
type PushWaitingScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushWaitingScreenRequest) Reset() {
	*x = PushWaitingScreenRequest{}
	mi := &file_bee_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushWaitingScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWaitingScreenRequest) ProtoMessage() {}

func (x *PushWaitingScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWaitingScreenRequest.ProtoReflect.Descriptor instead.
func (*PushWaitingScreenRequest) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{4}
}

type PushWaitingScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushWaitingScreenResponse) Reset() {
	*x = PushWaitingScreenResponse{}
	mi := &file_bee_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushWaitingScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWaitingScreenResponse) ProtoMessage() {}

func (x *PushWaitingScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bee_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWaitingScreenResponse.ProtoReflect.Descriptor instead.
func (*PushWaitingScreenResponse) Descriptor() ([]byte, []int) {
	return file_bee_api_proto_rawDescGZIP(), []int{5}
}

var File_bee_api_proto protoreflect.FileDescriptor

const file_bee_api_proto_rawDesc = "" +
	"\n" +
	"\rbee.api.proto\x12\x03bee\"\"\n" +
	"\x0ePushUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x11\n" +
	"\x0fPushUrlResponse\"\x14\n" +
	"\x12HealthCheckRequest\"%\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\bR\x02up\"\x1a\n" +
	"\x18PushWaitingScreenRequest\"\x1b\n" +
	"\x19PushWaitingScreenResponse2\xd4\x01\n" +
	"\x06BeeApi\x124\n" +
	"\aPushUrl\x12\x13.bee.PushUrlRequest\x1a\x14.bee.PushUrlResponse\x12@\n" +
	"\vHealthCheck\x12\x17.bee.HealthCheckRequest\x1a\x18.bee.HealthCheckResponse\x12R\n" +
	"\x11PushWaitingScreen\x12\x1d.bee.PushWaitingScreenRequest\x1a\x1e.bee.PushWaitingScreenResponseB\vZ\t./bee;beeb\x06proto3"

var (
	file_bee_api_proto_rawDescOnce sync.Once
	file_bee_api_proto_rawDescData []byte
)

func file_bee_api_proto_rawDescGZIP() []byte {
	file_bee_api_proto_rawDescOnce.Do(func() {
		file_bee_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bee_api_proto_rawDesc), len(file_bee_api_proto_rawDesc)))
	})
	return file_bee_api_proto_rawDescData
}

var file_bee_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bee_api_proto_goTypes = []any{
	(*PushUrlRequest)(nil),            // 0: bee.PushUrlRequest
	(*PushUrlResponse)(nil),           // 1: bee.PushUrlResponse
	(*HealthCheckRequest)(nil),        // 2: bee.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 3: bee.HealthCheckResponse
	(*PushWaitingScreenRequest)(nil),  // 4: bee.PushWaitingScreenRequest
	(*PushWaitingScreenResponse)(nil), // 5: bee.PushWaitingScreenResponse
}
var file_bee_api_proto_depIdxs = []int32{
	0, // 0: bee.BeeApi.PushUrl:input_type -> bee.PushUrlRequest
	2, // 1: bee.BeeApi.HealthCheck:input_type -> bee.HealthCheckRequest
	4, // 2: bee.BeeApi.PushWaitingScreen:input_type -> bee.PushWaitingScreenRequest
	1, // 3: bee.BeeApi.PushUrl:output_type -> bee.PushUrlResponse
	3, // 4: bee.BeeApi.HealthCheck:output_type -> bee.HealthCheckResponse
	5, // 5: bee.BeeApi.PushWaitingScreen:output_type -> bee.PushWaitingScreenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bee_api_proto_init() }
func file_bee_api_proto_init() {
	if File_bee_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bee_api_proto_rawDesc), len(file_bee_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bee_api_proto_goTypes,
		DependencyIndexes: file_bee_api_proto_depIdxs,
		MessageInfos:      file_bee_api_proto_msgTypes,
	}.Build()
	File_bee_api_proto = out.File
	file_bee_api_proto_goTypes = nil
	file_bee_api_proto_depIdxs = nil
}
